//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ArmAlsn.rc
//
#define IDR_SRVR_INPLACE                4
#define IDR_SRVR_INPLACE_256            5
#define IDR_SRVR_EMBEDDED               6
#define IDR_CNTR_INPLACE                7
#define IDD_ABOUTBOX                    100
#define IDS_STRING_TREY101              101
#define IDP_FAILED_TO_CREATE            102
#define IDP_OLE_INIT_FAILED             103
#define IDS_CPU                         104
#define IDR_HELP_MENU                   118
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ArmAlsnTYPE                 130
#define IDR_CONTEXT_MENU_MAIN           131
#define IDD_DIALOG_CONFIG               134
#define IDD_DIALOG_CONFIG_DIRECTX       135
#define IDD_DIALOG_CONFIG_SOUND         136
#define IDD_DIALOG_CONFIG_GPS           138
#define IDD_DIALOG_CONFIG_PATH          139
#define IDD_VIEW_PUT                    150
#define IDD_VIEW_ASIM                   151
#define ID_VIEW_OUTPUTWND               161
#define IDS_OUTPUT_WND                  162
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_OUTPUT_POPUP                182
#define IDS_CLOSE                       195
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDR_OSCILLOSCOPEFRAME           202
#define IDR_OSCILLOSCOPEFRAME_256       203
#define IDR_ALSDBFRAME                  204
#define IDR_ALSIZMFRAME                 205
#define IDR_DBVLISTYPE                  206
#define IDD_DBVLIST_FORM                207
#define IDR_VIEWPUTBIG                  208
#define IDR_VIEWPUTSMALL                209
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   303
#define IDD_ALSDBFORMVIEW               304
#define IDD_ALSIZMFORMVIEW              305
#define IDR_TOOLBAR1                    306
#define IDD_DIALOG_CONFIG_DIRECTX1      307
#define IDB_BITMAP1                     308
#define IDB_BITMAP2                     309
#define IDR_ALSDBFRAME_256              310
#define IDC_BUTTON1                     999
#define IDC_TREE1                       1000
#define IDC_NOSAVE                      1001
#define IDC_TAB1                        1002
#define IDC_DISKO                       1003
#define IDC_ITINERARY                   1004
#define IDC_COUPE                       1005
#define IDC_SAVE_EXIT                   1006
#define IDC_BUTTON_1COM                 1007
#define IDC_SOUND_DEVICE_COMBO          1008
#define IDC_ITINERARY_IZM               1009
#define IDC_COUPE_IZM                   1010
#define IDC_SAVECONFIG                  1011
#define IDC_PK_V_IZM                    1012
#define IDC_2_BUTTON_1COM               1013
#define IDC_LONGITUDE_IZM               1014
#define IDC_CAPTURE_DEVICE_COMBO        1015
#define IDC_OBGECT_IZM                  1016
#define IDC_SCHETP                      1017
#define IDC_OBGECT_IZM2                 1017
#define IDC_OBGECT_OLD_IZM              1017
#define IDC_CHECK_IZM                   1018
#define IDC_PROGRESS1                   1019
#define IDC_PROGRESS_H                  1019
#define IDC_CHECK_ADD                   1020
#define IDC_SLIDER1                     1021
#define IDC_CHECK_MAN                   1022
#define IDCONSAVE                       1023
#define IDC_STATIC_IZM                  1024
#define IDC_STIK                        1025
#define IDC_ADD_PK                      1026
#define IDC_INC_PK                      1027
#define IDC_START_IZM                   1028
#define IDC_FREC_R                      1029
#define IDC_FREC_RATE                   1030
#define IDC_TOK                         1031
#define IDC_TOK_IZM                     1032
#define IDC_ASCHEN1                     1033
#define IDC_ASCHEN2                     1034
#define IDC_ASIMETR                     1035
#define IDC_COMBO_PORT                  1036
#define IDC_ADD_10M                     1037
#define IDC_1_PK_V                      1038
#define IDC_2_PK_V                      1039
#define IDC_2_ASIMETR                   1040
#define IDC_2_ASCHEN1                   1041
#define IDC_2_ASCHEN2                   1042
#define IDC_2_COMBO_PORT                1043
#define IDC_DEC_10M                     1044
#define IDC_INC_10M                     1045
#define IDC_LATITUDE                    1046
#define IDC_LONGITUDE                   1047
#define IDC_LATITUDE_IZM                1049
#define IDC_MFCBUTTON1                  1050
#define IDC_KORECT                      1051
#define IDC_STOLB_KM                    1052
#define IDC_PKOK                        1053
#define IDC_SCHETM                      1054
#define IDC_EDIT_PATH_DB                1055
#define IDC_EDIT_PATH_WP                1056
#define IDC_EDIT_PATH_OZ                1057
#define IDC_BUTTON_FILE_DB              1058
#define IDC_BUTTON_FOLDER_WP            1059
#define IDC_BUTTON_FILE_OZ              1060
#define IDC_EDIT_ABOUT                  1061
#define IDC_OZI                         1062
#define IDC_VERFILE                     1063
#define IDC_DAILYBASIS                  1066
#define IDC_MAIL_LINK                   1070
#define IDC_CHECK1                      1071
#define IDC_MAP                         1071
#define IDC_PK_V_N                      1073
#define IDC_PK_V_K                      1074
#define ID_LANGUAGE_FIRST               32000
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_OSCILLOSCOPE                 32772
#define ID_CONFIG                       32773
#define ID_HIDE                         32775
#define ID_APP_UP                       32779
#define ID_DATABASE                     32780
#define ID_VIEW_STATUS_BAR_DB           32781
#define ID_BUTTON32782                  32782
#define ID_MyBass                       32783
#define ID_BUTTON32784                  32784
#define ID_32785                        32785
#define ID_DISCO                        32786
#define ID_1                            32786
#define ID_IZMALSN                      32787
#define ID_BUTTON32789                  32789
#define ID_TEC32790                     32790
#define ID_TEST                         32791
#define ID_32792                        32792
#define ID_32793                        32793
#define ID_OziMap                       32794
#define ID_32795                        32795
#define ID_INDICATOR_TIME               59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        322
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
